# conda env create --file conda.yaml
name: jaxneus
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.11
  - jaxlib=*=*cuda*
  - jax
  - cuda-nvcc
  - jaxtyping
  - optax
  - flax
  - PyMCubes
  - pip
  - pip:
    - -r requirements.txt